cursor_shape beam
cursor_blink_interval 0.6
font_size 12.0
font_family JetBrainsMono Nerd Font
background_opacity 0.8
background_blur 10
enable_gpu_renderer yes
shell zsh -c "fastfetch | lolcat; exec zsh"
