$text_color = rgba(C8F9FFFF)
$entry_background_color = rgba(1A0F2E99)
$entry_border_color = rgba(4DE8E088)
$entry_color = rgba(C8F9FFFF)
$font_family = Inter
$font_family_clock = Inter
$font_material_symbols = Inter
